### ISSUE TITLE
Hackage version still requires text <1.3

### ISSUE THREAD

**Issue by dpwiz** [haskell-text/text-display#24]
https://hackage.haskell.org/package/text-display-0.0.2.0/dependencies

It should get some <3 :smile:

**Comment by Kleidukos** [comment]
Good catch!

**Comment by Kleidukos** [comment]
@dpwiz Do you need a release to be made post-haste or can you depend on a Github tag?

**Comment by dpwiz** [comment]
The most recent Hackage version still wants `text-1.2`.

**Comment by Kleidukos** [comment]
@dpwiz Hi, it's done. :) Could you please try `0.0.3.0` and tell me if this is okay for you?

**Comment by dpwiz** [comment]
I haven't actually tried it, but the Hackage says it requires `text >= 2` which is unexpected. I suspect that wasn't intentional as the previous version worked fine with `text < 2`.
