### ISSUE TITLE
Allow deriving for records where all the fields have a Display instance

### ISSUE THREAD

**Issue by JonathanLorimer** [haskell-text/text-display#51]
It would be nice if you could deriving display instances for records where all the fields have a `Display` instance

**Comment by Kleidukos** [comment]
Indeed.

**Comment by JonathanLorimer** [comment]
@Kleidukos if you have any advice on how to do this, I would be happy to take a run at it. I figure you can probably do it with a deriving via generic (or something to that effect)

**Comment by Kleidukos** [comment]
@JonathanLorimer Yes this would be something along the lines of https://github.com/tchoutri/pg-entity/blob/main/src/Database/PostgreSQL/Entity/Types.hs#L87-L173 but it's a pain to understand if you've never done it before. Would you like to pair with me on this? :)

**Comment by JonathanLorimer** [comment]
@Kleidukos I have a solution almost done, will put up a draft PR for your initial review

**Comment by Kleidukos** [comment]
fixed by #52 thanks again @JonathanLorimer
