### ISSUE TITLE
Failed to load interface for 'Data.Text.Display.Generic'

### ISSUE THREAD

**Issue by JonathanLorimer** [haskell-text/text-display#54]
* Display version:  692250f3531a457b21db67799a524379462e4bab
* GHC version: 9.4.4
* Cabal version: 3.11

I am getting an error about a "dyn" library when trying to use this package:

```
<no location info>: error:
    Failed to load interface for ‘Data.Text.Display.Generic’
There are files missing in the ‘text-display-0.0.4.0-FociJmAHppxH1KLWbBkTyi’ package,
try running 'ghc-pkg check'.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

**Comment by JonathanLorimer** [comment]
Wow, bad error message. I thought you could prevent files in a library from being exported by not including them, that was my bad. Thanks for fixing.

**Comment by Kleidukos** [comment]
Glad to hear. :)
